on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - uses: actions/checkout@v2
      - run: make all
      - uses: valist-io/valist-github-action@dev
        with:
          rpc-url: https://rpc.valist.io/mumbai
          private-key: ${{ secrets.PRIVATE_KEY }}
          account: nasdf
          project: example-go-multi-platform
          release: ${{ github.ref_name }}
          path: './dist'
          install_name: hello
          install_darwin_amd64: darwin-amd64/hello
          install_darwin_arm64: darwin-arm64/hello
          install_linux_amd64: linux-amd64/hello
          install_linux_arm64: linux-arm64/hello
          install_windows_amd64: linux-amd64/hello.exe